Vagrant.configure("2") do |config|
    # Use a specific base box with a Linux distribution of your choice
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "ubuntu-ebpf-testing-box"

    config.vm.provision :shell, :privileged => false, :path => "scripts/setup.sh"

    # Forward necessary ports (e.g., if you are working with networking-related eBPF programs)
    config.vm.network "forwarded_port", guest: 80, host: 8080
  
    # sync examples folder over to vagrant vm
    config.vm.synced_folder "./examples", "/examples"
  
    # Specify the provider (VirtualBox, VMware, etc.)
    config.vm.provider "virtualbox" do |vb|
      # Customize virtual machine settings if needed
      vb.memory = "4096"
    #   vb.cpus = 2
    end
  end